before:
  hooks:
    - go mod tidy

builds:
  - id: main
    env:
      - GO111MODULE=on  # TODO: remove
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        # Compress the binary.
        - upx --best --lzma "{{ .Path }}"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
