before:
  hooks:
    - go mod download
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
