package main

import (
	"flag"
	"github.com/pcasteran/terraform-graph-beautifier/cytoscape"
	"github.com/pcasteran/terraform-graph-beautifier/graphviz"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"os"
	"path/filepath"
)

func getWorkingDir() string {
	dir, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return filepath.Base(dir)
}

func main() {
	// Prepare command line options.
	inputFilePath := flag.String("input", "", "Path of the input Graphviz file to read, if not set 'stdin' is used")
	outputFilePath := flag.String("output", "", "Path of the output Graphviz file to write, if not set 'stdout' is used")
	debug := flag.Bool("debug", false, "Prints debugging information to stderr")
	// Input reading options.
	var excludePatterns arrayFlags
	flag.Var(&excludePatterns, "exclude", "Pattern (regexp) of the resource to filter out (can be repeated multiple times)")
	keepTfJunk := flag.Bool("keep-tf-junk", false, "Do not remove the \"junk\" nodes and edges generated by 'terraform graph' (default false)")
	// Output writing options.
	graphName := flag.String("graph-name", "", "Name of the Graphviz graph to create (default working directory name)")
	embedModules := flag.Bool("embed-modules", false, "Embed a module sub-graph inside its parent; can lead to really huge graphs (default false)")

	// Parse command line arguments.
	flag.Parse()
	if *graphName == "" {
		cwd := getWorkingDir()
		graphName = &cwd
	}

	// Configure logging.
	// Default level for this example is info, unless debug flag is present.
	zerolog.SetGlobalLevel(zerolog.InfoLevel)
	if *debug {
		zerolog.SetGlobalLevel(zerolog.DebugLevel)
	}
	log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})

	// Load the graph from the specified input.
	tfGraph, dependencies := graphviz.LoadGraph(*inputFilePath, *keepTfJunk, excludePatterns)

	// Write the result to the specified output.
	// TODO : output type
	formattingOptions := &cytoscape.FormattingOptions{
		GraphName:    *graphName,
		EmbedModules: *embedModules,
	}
	cytoscape.WriteGraph(*outputFilePath, tfGraph, dependencies, formattingOptions)
}
