name: Pull request lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:

  validate_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Allowed types, see https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
